services:
  db:
    image: mysql
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
volumes:
  db_volume: